### ISSUE TITLE
Request to Release Code for This Repository

### ISSUE THREAD

**Issue by DorothyDUUU** [QwenLM/ConsisEval#1]
Hello,

Thank you for the good work.

I'm wondering if you have any plans to release the source code for this repo in the near future? I believe that your work would be incredibly valuable to me.

Thank you very much for your efforts and for sharing your work.

Best regards,

**Comment by Zhe-Young** [comment]
Hi,
Our data and code has been released.
Thanks for your interest in our work, and hope it can benefit your research!
